<a href="https://colab.research.google.com/github/Firoz-kumar-3/Git/blob/master/train_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.arange(0,100,1)

In [3]:
len(x)

100

In [13]:
def train_test_split(x,test_size):
  number=int((test_size/100)*len(x))
  train_size=len(x)-number
  train=x[ :train_size]
  test=x[train_size: ]
  return train,test

In [14]:
train_test_split(x,30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
        87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]))

In [19]:
def train_test_split(x,test_size):
  x1=np.random.shuffle(x)
  number=int((test_size/100)*len(x))
  train_size=len(x)-number
  train=x[ :train_size]
  test=x[train_size: ]
  return train,test

In [20]:
train_test_split(x,30)

(array([87, 19, 79, 91, 23, 27, 48, 17, 46, 78, 11,  1, 67, 15, 28,  4, 95,
        82, 99, 62,  2, 81, 16, 80, 40, 72, 42, 64,  8, 73, 86, 36, 65, 94,
        75, 34, 20, 60,  3, 71, 83, 13, 77, 74, 24, 63, 12, 88, 98,  6, 70,
        37, 50, 22, 92, 49, 43, 96, 53, 68, 33,  7, 35, 31, 69,  9, 10, 97,
        76, 51]),
 array([21, 32, 66, 58, 89,  0, 61, 41, 47, 55, 14, 93, 26, 39, 84, 54, 57,
        29, 59, 56, 44, 45, 30,  5, 25, 85, 38, 52, 18, 90]))